
spring.main.web-application-type=none

spring.main.headless=false
#office
#server.url=http://192.168.1.3:8080
#my
server.url=http://10.212.198.133:8080
#room
#server.url=http://172.26.121.133:8080

tracker.process.mode=VISIBLE

#tracker.process.mode=ALL




logging.level.com.tracker=INFO

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n