name: Build Tracker Agent Installer

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build Jar
        run: mvn clean package -DskipTests

      - name: Prepare Dist
        shell: cmd
        run: |
          mkdir dist
          copy target\tracker-backend-0.0.1-SNAPSHOT.jar dist\

      - name: Create Installer
        shell: cmd
        run: |
          jpackage ^
          --type exe ^
          --name TrackerAgent ^
          --vendor "HANSETECH SOFT SOLUTION PRIVATE LIMITED" ^
          --app-version 1.0.0 ^
          --input dist ^
          --main-jar tracker-backend-0.0.1-SNAPSHOT.jar ^
          --win-shortcut ^
          --win-menu ^
          --win-dir-chooser ^
          --win-per-user-install ^
          --install-dir TrackerAgent ^
          --dest installer

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: TrackerAgentSetup
          path: installer
